## Read the data

This code will give you the data you will use for this PC:

In [157]:
# read web table into pandas DF
import pandas as pd

co2Link='https://docs.google.com/spreadsheets/d/e/2PACX-1vRXjfxeKHQBBCh_oHP-D6RIHEX4eduLjydHb6ZGsU4jo0IK0KKQSoYX_X1FGssC_9hnqCgjKN0K4AVf/pub?gid=775098192&single=true&output=csv'
carbon=pd.read_csv(co2Link)

In [158]:
# here it is:
carbon

,name,metric tonnes of CO2,date_of_information,ranking,region
0,China,1.219600e+10,2023,1,East and Southeast Asia
1,United States,4.795000e+09,2023,2,North America
2,India,2.821000e+09,2023,3,South Asia
3,Russia,1.844000e+09,2023,4,Central Asia
4,Japan,9.602300e+08,2023,5,East and Southeast Asia
...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,212,South America
212,Montserrat,2.400000e+01,2023,213,Central America and the Caribbean
213,Antarctica,1.500000e+01,2023,214,Antarctica
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,215,Africa
215,Niue,9.000000e+00,2023,216,Australia and Oceania

As you see, some columns have space, which should be deleted:

In [159]:
# also
carbon.columns

Index(['name', 'metric tonnes of CO2', 'date_of_information', 'ranking',
       'region'],
      dtype='object')

In [160]:
# Like this
carbon.rename(columns={'metric tonnes of CO2':'metric_tonnes_of_CO2'},inplace=True)

# see
carbon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  216 non-null    object
 1   metric_tonnes_of_CO2  216 non-null    float64
 2   date_of_information   216 non-null    int64
 3   ranking               216 non-null    int64
 4   region                216 non-null    object
dtypes: float64(1), int64(2), object(2)
memory usage: 8.6+ KB

You always make a copy:

In [161]:
carbon_copy=carbon.copy()

## Questions

Complete the tasks requested using **carbon_copy**:

1. Keep all the columns but _Ranking_:
    * Tip: use [drop](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html), [loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html), and [iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html) for the same purpose (three ways to accomplish the task).

2. Find the country with the minimum CO2 emission in the world.

3. Find the country with the minimum CO2 emission per Region.

4. Create a new column by keeping the square root of the the original CO2  column.

5. Compute the average of CO2. Then, create a new column. This new column is
the original CO2 minus the average computed.

You have changed **carbon_copy**, now save it as a file like this:

In [162]:
# carbon_copy.to_csv("carbon_copy.csv",index=False)

In [163]:
# Pregunta 1

eliminarColumnas=["ranking"]
# se utiliza el drop para eliminar la columna ranking del DataFrame
carbon_copy.drop(columns=eliminarColumnas, inplace=True)
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region
0,China,1.219600e+10,2023,East and Southeast Asia
1,United States,4.795000e+09,2023,North America
2,India,2.821000e+09,2023,South Asia
3,Russia,1.844000e+09,2023,Central Asia
4,Japan,9.602300e+08,2023,East and Southeast Asia
...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean
213,Antarctica,1.500000e+01,2023,Antarctica
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa
215,Niue,9.000000e+00,2023,Australia and Oceania

In [164]:
# Pregunta 2

minimo_CO2=carbon_copy[carbon_copy.metric_tonnes_of_CO2==carbon_copy.metric_tonnes_of_CO2.min()]["name"]
minimo_CO2

215    Niue
Name: name, dtype: object

In [165]:
# Pregunta 3

# se agrupan los datos de carbon_copy DataFrame por "regiÃ³n"
grupos_por_region=carbon_copy.groupby("region")
# se encuentra el mÃ­nimo valor de emisiones de CO2 dentro de cada grupo
minimo_CO2_por_region=grupos_por_region["metric_tonnes_of_CO2"].min()
minimo_CO2_por_region

region
Africa                                    12.0
Antarctica                                15.0
Australia and Oceania                      9.0
Central America and the Caribbean         24.0
Central Asia                         7144000.0
East and Southeast Asia                  660.0
Europe                                   742.0
Middle East                          3913000.0
North America                             57.0
South America                             36.0
South Asia                               733.0
Name: metric_tonnes_of_CO2, dtype: float64

In [166]:
# pregunta 4

# esta linea calcula la raiz cuadrada de cada valor de la columna "metric_tonnes_of_CO2"
nuevaColumna=carbon_copy["metric_tonnes_of_CO2"]**0.5

# se crea una nueva columna en carbon_copy DataFrame
carbon_copy=carbon_copy.assign(raiz_cuadrada_CO2=nuevaColumna)
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region,raiz_cuadrada_CO2
0,China,1.219600e+10,2023,East and Southeast Asia,110435.501538
1,United States,4.795000e+09,2023,North America,69245.938509
2,India,2.821000e+09,2023,South Asia,53113.086900
3,Russia,1.844000e+09,2023,Central Asia,42941.821107
4,Japan,9.602300e+08,2023,East and Southeast Asia,30987.578156
...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America,6.000000
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean,4.898979
213,Antarctica,1.500000e+01,2023,Antarctica,3.872983
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa,3.464102
215,Niue,9.000000e+00,2023,Australia and Oceania,3.000000

In [167]:
# pregunta 5

# se halla el promedio
promedio_CO2=carbon_copy["metric_tonnes_of_CO2"].mean()

carbon_copy=carbon_copy.assign(CO2_diferencia=carbon_copy["metric_tonnes_of_CO2"]-promedio_CO2)

carbon_copy.to_csv("carbon_copy.csv",index=False)
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region,raiz_cuadrada_CO2,CO2_diferencia
0,China,1.219600e+10,2023,East and Southeast Asia,110435.501538,1.202444e+10
1,United States,4.795000e+09,2023,North America,69245.938509,4.623435e+09
2,India,2.821000e+09,2023,South Asia,53113.086900,2.649435e+09
3,Russia,1.844000e+09,2023,Central Asia,42941.821107,1.672435e+09
4,Japan,9.602300e+08,2023,East and Southeast Asia,30987.578156,7.886654e+08
...,...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America,6.000000,-1.715645e+08
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean,4.898979,-1.715645e+08
213,Antarctica,1.500000e+01,2023,Antarctica,3.872983,-1.715645e+08
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa,3.464102,-1.715646e+08
215,Niue,9.000000e+00,2023,Australia and Oceania,3.000000,-1.715646e+08